services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env  # Ensure this file exists
    volumes:
      - ./backend:/app   # Mount the backend folder
    restart: always


  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.local
    restart: always
    depends_on:
      - backend